version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    platform: linux/amd64
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    platform: linux/amd64
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    platform: linux/amd64
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    platform: linux/amd64
    image: udagram-frontend:local